#!/usr/bin/env bash
# vim:tw=0:ts=2:sw=2:et:norl:ft=sh
# Author: Landon Bouma (landonb &#x40; retrosoft &#x2E; com)
# Project: https://github.com/landonb/home-fries#🍟
# License: MIT

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

_hf_check_deps_termdo_all () {
  # Verify distro_util.sh loaded.
  check_dep 'suss_window_manager' || return $?
  _hf_check_deps_check_not_macos || return $?
  return 0
}

_hf_check_deps_check_not_macos () {
  check_dep 'os_is_macos' || return $?
  os_is_macos || return 0
  echo 'This command is not supported on Darwin' 1>&2
  return 1
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

# Send commands to all the terminal windows.

# But first,
#  some xdotool notes...
#
# If you don't specify what to search, xdotool adds to stderr,
#   "Defaulting to search window name, class, and classname"
# We can search for the app name using --class or --classname.
#   xdotool search --class "mate-terminal"
# Translate the window IDs to their terminal titles:
#   xdotool search --class "mate-terminal" | xargs -d '\n' -n 1 xdotool getwindowname
# 2016-05-04: Note that the first window in the list is named "Terminal",
#   but it doesn't correspond to an actual terminal, it doesn't seem.
#     $ RESPONSE=$(xdotool windowactivate 77594625 2>&1)
#     $ echo $RESPONSE
#     XGetWindowProperty[_NET_WM_DESKTOP] failed (code=1)
#     $ echo $?
#     0
#   What's worse is that that window hangs on activate.
#     $ xdotool search --class mate-terminal -- windowactivate --sync %@ type "echo 'Hello buddy'\n"
#     XGetWindowProperty[_NET_WM_DESKTOP] failed (code=1)
#     [hangs...]
#   Fortunately, like all problems, this one can be solved with bash, by
#   checking the desktop of the terminal window before sending it keystrokes.

termdo-all () {
  _hf_check_deps_termdo_all || return $?
  suss_window_manager
  local THIS_WINDOW_ID=$(xdotool getactivewindow)
  local WINDOW_IDS=$(get_terminal_window_ids)
  local winid
  for winid in ${WINDOW_IDS}; do
    # Don't send the command to this window, at least not yet, since it'll
    # end up on stdin of this fcn. and won't be honored as a bash command.
    if [ ${THIS_WINDOW_ID} -ne ${winid} ]; then
      # See if this is a legit window or not.
      local DESKTOP_NUM=$(xdotool get_desktop_for_window ${winid} 2> /dev/null)
      # For real terminal, the number is 0 or greater;
      # for the fakey, it's 0, and also xdotool returns 1.
      if [ $? -eq 0 ]; then
        # This was my first attempt, before realizing the obvious.
        #   if false; then
        #     xdotool windowactivate --sync $winid
        #     sleep .1
        #     xdotool type "echo 'Hello buddy'
        ##"
        #     # Hold on a millisec, otherwise I've seen, e.g., the trailing
        #     # character end up in another terminal.
        #     sleep .2
        #   fi
        # And then this is the obvious:

        # Oh, wait, the type and key commands take a window argument...
        # NOTE: Without the quotes, e.g., xdotool type --window $winid $*,
        #       you'll have issues, e.g., xdotool sudo -K
        #       shows up in terminals as, sudo-K: command not found
        # NOTE: If you've bash'ed within a session, you'll find all 'em.
        #       And you'll xdotool them all. But not a big deal?
        xdotool windowactivate --sync ${winid} type "$*"
        # Note that 'type' isn't always good with newlines, so use 'key'.
        # 2018-02-14 16:42: Revisit that comment. Docs make it seem like newlines ok.
        xdotool windowactivate --sync ${winid} key Return
      fi
    fi
  done
  # Bring original window back to focus.
  xdotool windowactivate --sync ${THIS_WINDOW_ID}
  # Now we can do what we did to the rest to ourselves.
  eval $*
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

# Test:
if false; then
  termdo-all "echo Wake up get outta bed
"
fi

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

# 2021-02-20: This function is unused.
termdo-reset () {
  _hf_check_deps_termdo_all || return $?
  suss_window_manager
  local THIS_WINDOW_ID=$(xdotool getactivewindow)
  local WINDOW_IDS=$(get_terminal_window_ids)
  local winid
  for winid in $WINDOW_IDS; do
    if [ $THIS_WINDOW_ID -ne $winid ]; then
      local DESKTOP_NUM=$(xdotool get_desktop_for_window $winid 2> /dev/null)
      if [ $? -eq 0 ]; then
        # Note that the terminal from whence this command is being run
        # will get the keystrokes -- but since the command is running,
        # the keystrokes sit on stdin and are ignored. Then along comes
        # the ctrl-c, killing this fcn., but not until after all the other
        # terminals also got their fill.

        xdotool windowactivate --sync ${winid} key ctrl+c
        xdotool windowactivate --sync ${winid} type "cd $1"
        # Hrmm. 'Ctrl+c' and 'ctrl+c' are acceptable, but 'return' is not.
        xdotool windowactivate --sync ${winid} key Return
      fi
    fi
  done
  # Bring original window back to focus.
  xdotool windowactivate --sync ${THIS_WINDOW_ID}
  # Now we can act locally after having acted globally.
  cd $1
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

# 2021-02-20: This function is unused.
termdo-cmd () {
  _hf_check_deps_termdo_all || return $?
  suss_window_manager
  local THIS_WINDOW_ID=$(xdotool getactivewindow)
  local WINDOW_IDS=$(get_terminal_window_ids)
  local winid
  for winid in $WINDOW_IDS; do
    if [ $THIS_WINDOW_ID -ne ${winid} ]; then
      local DESKTOP_NUM=$(xdotool get_desktop_for_window ${winid} 2> /dev/null)
      if [ $? -eq 0 ]; then

        xdotool windowactivate --sync ${winid} key ctrl+c
        xdotool windowactivate --sync ${winid} key ctrl+d
        xdotool windowactivate --sync ${winid} type "$1"
        # Hrmm. 'Ctrl+c' and 'ctrl+c' are acceptable, but 'return' is not.
        xdotool windowactivate --sync ${winid} key Return
      fi
    fi
  done
  # Bring original window back to focus.
  xdotool windowactivate --sync ${THIS_WINDOW_ID}
  # Now we can act locally after having acted globally.
  eval $1
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

# 2021-02-20: This function is unused.
termdo-sudo-reset () {
  _hf_check_deps_termdo_all || return $?
  # sudo security
  # -------------
  # Make all-terminal fcn. to revoke sudo on all terms,
  # to make up for security hole of leaving terminals sudo-ready.
  # Then again, real reason against is doing something dumb,
  # so really you should always be sudo-promted.
  # But maybe the answer is really a confirm prompt,
  # not a password prompt (like in Windows, ewwwww!). -summer2016
  termdo-all "echo termdo-sudo-reset says"
  termdo-all sudo -K
}

# FIXME/MAYBE: Add a close-all fcn:
#               1. Send ctrl-c
#               2. Send exit one or more times (to exit nested shells)

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

get_terminal_window_ids () {
  # 2018-02-14: `xdotool search` is returning 1 more than the number of
  # mate-terminals. I thought it was if I ran bash within bash within a
  # terminal, but that wasn't the case. Not sure what it is. But there's
  # another way we can get exactly what we want, with `wmctrl` instead.
  #   xdotool search --class "${WM_TERMINAL_APP}"
  wmctrl -l -x | grep "${WM_TERMINAL_APP}" | awk '{print $1}'
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

# 2021-02-20: This function is unused.
termdo-bash-reset () {
  _hf_check_deps_termdo_all || return $?
  # Verify session_util.sh loaded.
  check_dep 'bash-exit-bash-hole' || return $?

  # We could care or not whether we stacking subshells (i.e., calling
  # `bash` multiple times from the same terminal) -- it doesn't affect
  # performance.
  #
  # Nonetheless, if you like a mostly clean house, we can exit any
  # subshells first to minimize the depth of the bash hole we make.
  #
  # One approach might be to use kill. But then how do you distinguish
  # between a terminal that's in a subshell vs one that's not?
  # If you look at `ps aux | grep bash`, you'll see that the top-level
  # terminal processes are just 'bash', and subshells created are
  # generally '/bin/bash' (because our "alias bash=" calls /bin/bash,
  # and not just bash).
  #
  # So this could work, but it's blindly destructive:
  #
  #    kill -s 9 $(ps aux | grep "/bin/bash" | awk '{print $2}')
  #
  # We can be a bit more intelligent, and respect, say, a running
  # process, by sending an exit-maybe signal ahead of the /bin/bash.
  #
  # Note also the backgrounded and the sleep. 2 termdo-all's in a row
  # don't work from the same shell (the second is apparently ignored),
  # so sub-shell the first call and sleep to make it work.
  termdo-all bash-exit-bash-hole &

  #  sleep 0.5
  sleep 1.0

  # FIXME/2020-09-01: Does this still work now that `/bin/bash` → `/usr/bin/env bash`?
  termdo-all /bin/bash
}

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

# Run the function if being executed.
# Otherwise being sourced, so do not.
if ! $(printf %s "$0" | grep -q -E '(^-?|\/)(ba|da|fi|z)?sh$' -); then
  termdo-all "$@"
fi

