#!/bin/bash
# File: setup.sh
# Author: Landon Bouma (landonb &#x40; retrosoft &#x2E; com)
# Last Modified: 2016.10.09
# Project Page: https://github.com/landonb/home-fries
# Summary: Private Dotfiles Recipe
# License: GPLv3
# vim:tw=0:ts=2:sw=2:et:norl:
set -e

echo "2016-10-09: This script still under development..."
exit 1

# FIXME: Build user's curly clone from ground up and point back to this repo.
# - ask where to install
# - set it up, including git init

# USAGE: Run this script to setup a new private dotfiles repo,
#        or to reface an existing private dotfiles repository.
#        - For a new install, you can set USERS_CURLY to your
#          desired path, or you'll be asked to specify one.
#        - For an existing install, just run the script;
#          it'll figure it out.

# Get the relative path to this script.
SCRIPT_DIR="$(dirname ${BASH_SOURCE[0]})"
# Get the absolute path, for symlinks.
CANON_CURLY=$(readlink -f $SCRIPT_DIR)
# Get the name of just the directory it's in.
CANON_BNAME=$(basename ${CANON_CURLY})

function errexit_cleanup () {
    echo
    echo "ERROR: The script failed!!"
    # No exit necessary, unless we want to specify status.
    exit 1
}
trap errexit_cleanup EXIT

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

setup_users_curly_path () {
  local CANDIDATES=()
  if [[ -z ${USERS_CURLY} ]]; then

    # First try to find it under ~/.
    while IFS= read -r -d '' file; do
      #echo "Checking candidate at: $file"
      # Check if this dir contains the working private dotfiles...
      if [[ -e ${file}/master_chef ]]; then
        #echo "found: ${file}/master_chef"
        # for the main development machine;
        CANDIDATES+=("${file}")
      elif [[ -e ${file}/junior_chef ]]; then
        #echo "found: ${file}/junior_chef"
        # or for a satellite machine.
        CANDIDATES+=("${file}")
      fi
    # HA. HA. HA!
    # http://unix.stackexchange.com/questions/272698/why-is-the-array-empty-after-the-while-loop
    done < <(find ${HOME} -maxdepth 1 -type d ! -path . -name '.*' -print0)

    #echo "No. candidates found: ${#CANDIDATES[@]}"
    if [[ ${#CANDIDATES[@]} -gt 1 ]]; then
      echo "WARNING: More than one candidate found."
      for ((i = 0; i < ${#CANDIDATES[@]}; i++)); do
        CANDIDATE="${CANDIDATES[$i]}"
        echo "CANDIDATE: ${CANDIDATE}"
      done
      echo
      CANDIDATES=()
    elif [[ ${#CANDIDATES[@]} -lt 1 ]]; then
      echo "Welcome to curly!"
      echo
      echo "Please specify where to make your private dotfiles repository."
      #echo
      echo -n "Path to destination [~/.mydots]: "
      read -e USERS_CURLY
      #echo
      if [[ -z ${USERS_CURLY} ]]; then
        USERS_CURLY=${HOME}/.mydots
      fi
    else
      USERS_CURLY=${CANDIDATES[0]}
    fi
  fi

  if [[ -z ${USERS_CURLY} ]]; then
    echo "FATAL: Destination path not indicated."
    exit 1
  fi
  if [[ ! -d ${USERS_CURLY} ]]; then
    if [[ -e ${USERS_CURLY} ]]; then
      echo "FATAL: Destination path exists but is not a directory."
      exit 1
    fi
    echo "NOTICE: Destination path does not exist. Attempting to make it at: ${USERS_CURLY}"
    /bin/mkdir ${USERS_CURLY}
    # We `set -e` above, so if we're here, it worked.
  fi
  USERS_BNAME=$(basename ${USERS_CURLY})
  #echo
  echo "Using curly destination at: ${USERS_CURLY}"
} # end: setup_users_curly_path

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

install_destination_gitignore () {

  echo "Setting up ${USERS_CURLY}/.gitignore"

  pushd ${SCRIPT_DIR}/recipe &> /dev/null

  TMP_PATH=${USERS_CURLY}/.gitignore-$(date +%Y-%m-%d-%s)

  cat > ${TMP_PATH} << EOF
# NOTICE: This file was generated by ${CANON_BNAME}/$(basename $0).
# ${CANON_BNAME} makes symlinks back to all its own files.
# Everything under ${CANON_BNAME}/recipe is listed here.
# Feel free to add additional files of your own.

# If you'd like to designate one machine as your main development machine
# (generally the machine whose hard drives you backup, since your satellite
# machines are toss-away-able, right?), make a master_chef touchfile.
# On the satellite machines, make junior_chef touchfiles. Don't touchme bro.
master_chef
junior_chef
EOF

  git ls-files >> ${TMP_PATH}

  if [[ ! -e ${USERS_CURLY}/.gitignore ]]; then
    /bin/mv ${TMP_PATH} ${USERS_CURLY}/.gitignore
  else
    set +e
    diff ${TMP_PATH} ${USERS_CURLY}/.gitignore &> /dev/null
    RVAL=$?
    set -e
    if [[ ${RVAL} -ne 0 ]]; then
      echo "  NOTICE: .gitignore changed. Try this:"
      #echo
      echo "    meld ${USERS_CURLY}/.gitignore ${TMP_PATH} &"
      echo "    rm ${TMP_PATH}"
      echo "    rm ${USERS_CURLY}/.gitignore-*"
      #echo
    else
      echo "Not changed: ${USERS_CURLY}/.gitignore"
      /bin/rm ${TMP_PATH}
    fi
  fi

  popd &> /dev/null

} # end: install_destination_gitignore

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

install_destination_cfg () {

  echo "Setting up ${USERS_CURLY}/cfg"

  pushd ${USERS_CURLY} &> /dev/null

  mkdir -p cfg
  cd cfg

  /bin/ln -sf ${CANON_CURLY}/recipe/cfg/sync_repos.sh-example
  if [[ ! -e sync_repos.sh ]]; then
    /bin/cp -a ${CANON_CURLY}/cfg/sync_repos.sh-example sync_repos.sh
    echo
    echo "  If you'd like to use \`packme\` or \`unpack\`, edit cfg/sync_repos.sh, and also"
    echo "    git add cfg/sync_repos.sh && git commit -m 'Add 'cfg/sync_repos.sh'"
  else
    echo "  Already setup: cfg/sync_repos.sh"
  fi

  /bin/ln -sf ${CANON_CURLY}/recipe/cfg/travel_tasks.sh-example
  if [[ ! -e travel_tasks.sh ]]; then
    /bin/cp -a ${CANON_CURLY}/cfg/travel_tasks.sh-example travel_tasks.sh
    echo
    echo "  If you'd like to enhance \`packme\` or \`unpack\`, edit cfg/travel_tasks.sh, and also"
    echo "    git add cfg/travel_tasks.sh && git commit -m 'Add 'cfg/travel_tasks.sh'"
  else
    echo "  Already setup: cfg/travel_tasks.sh"
  fi

  popd &> /dev/null

} # end: install_destination_cfg

# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #

pump_n_dump () {

  setup_users_curly_path

  install_destination_gitignore

  install_destination_cfg

# FIXME: more stuff

}

pump_n_dump $*

echo "Thanks for playing!"

# Unhook errexit_cleanup.
trap - EXIT

exit 0

