# 2020-02-06: Generated by git@github.com:junegunn/fzf.git:install

# Setup fzf
# ---------
#
# (lb): To migrate to Zoidy Pooh Ansible task, I either need
#       to call fzf/install, or I need to go-get-install it.
#       The install script is interactive...
#
if [[ ! "$PATH" == */kit/working/golang/fzf/bin* ]]; then
  export PATH="${PATH:+${PATH}:}/kit/working/golang/fzf/bin"
fi

# Auto-completion
# ---------------
[[ $- == *i* ]] && source "/kit/working/golang/fzf/shell/completion.bash" 2> /dev/null

# Key bindings
# ------------
source "/kit/working/golang/fzf/shell/key-bindings.bash"

